// <auto-generated />
namespace Innoventory.Lotus.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _14072015_AL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_14072015_AL));
        
        string IMigrationMetadata.Id
        {
            get { return "201507141222435_14072015_AL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
